import Head from 'next/head';
import Hero from '../components/Hero';
import Navbar from '../components/Navbar';
import Catalog from '../components/Catalog';
import Market from '../components/Market';
import News from '../components/News';
import Contact from '../components/Contact';

export default function Home() {
  return (
    <>
      <Head>
        <title>Gudang Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Catalog />
      <Market />
      <News />
      <Contact />
    </>
  )
}
